import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'package:field_guard_re/core/services/background_location_service.dart';
import 'package:field_guard_re/core/services/debug_log_service.dart';

/// Thin wrapper around [FlutterLocalNotificationsPlugin] for the immediate,
/// non-scheduled notifications this app fires — currently the geofence
/// enter/exit alerts. Single source of truth so channel setup and permission
/// requests live in one place.
class NotificationService {
  NotificationService._();
  static final NotificationService instance = NotificationService._();

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  /// Shared id for the transient geofence enter/exit alert. The same id is
  /// used whether the alert is fired from the UI isolate or the background
  /// service isolate, so the two never stack a duplicate — a later `show`
  /// with this id overwrites the earlier one.
  static const int geofenceAlertId = 7001;

  /// Android channel for geofence arrival/departure alerts. High importance so
  /// it surfaces a heads-up banner even when the app is backgrounded.
  static const _channel = AndroidNotificationChannel(
    'geofence_alerts',
    'Geofence Alerts',
    description: 'Notifies when you reach or leave a task location.',
    importance: Importance.high,
  );

  /// Low-importance channel for the persistent background-location foreground
  /// service notification (the always-on "tracking" banner). Low importance so
  /// it stays silent and unobtrusive.
  static final _fgServiceChannel = AndroidNotificationChannel(
    BackgroundLocationService.channelId,
    'Location Tracking',
    description: 'Keeps your location updating for assigned tasks.',
    importance: Importance.low,
  );

  /// High-importance channel for FCM push alerts surfaced while the app is in
  /// the foreground (cheque received, task assigned, etc.). Separate from the
  /// geofence channel so the user can mute one without the other.
  static const _pushChannel = AndroidNotificationChannel(
    'push_alerts',
    'Notifications',
    description: 'Cheque, task and account notifications.',
    importance: Importance.high,
  );

  bool _initialised = false;

  /// Called when the user taps a notification carrying a [payload] (FCM pushes
  /// pass their JSON data map). Set by [PushNotificationService] to deep-link.
  /// Payload-less notifications (geofence alerts) never invoke this.
  void Function(String payload)? onTap;

  /// One-time setup: registers the channel and requests notification
  /// permission (Android 13+ / iOS). Safe to call more than once.
  Future<void> init() async {
    if (_initialised) return;
    _initialised = true;

    try {
      // Small icon = white silhouette drawable (Android tints it; a colourful
      // mipmap would render as a white blob). Generated by tool/gen_notif_icon.py.
      const androidInit =
          AndroidInitializationSettings('@drawable/ic_notification');
      const iosInit = DarwinInitializationSettings();
      await _plugin.initialize(
        const InitializationSettings(android: androidInit, iOS: iosInit),
        onDidReceiveNotificationResponse: (response) {
          final payload = response.payload;
          if (payload != null && payload.isNotEmpty) onTap?.call(payload);
        },
      );

      final android = _plugin.resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>();
      if (android != null) {
        await android.createNotificationChannel(_channel);
        await android.createNotificationChannel(_fgServiceChannel);
        await android.createNotificationChannel(_pushChannel);
        final granted = await android.requestNotificationsPermission();
        await DebugLogService.instance
            .log('[notification] init ok android permission=$granted');
      }
    } catch (e, st) {
      // Don't leave _initialised=true if init crashed — let it retry next time.
      _initialised = false;
      await DebugLogService.instance
          .log('[notification] init FAILED err=$e $st');
      rethrow;
    }

    final ios = _plugin.resolvePlatformSpecificImplementation<
        IOSFlutterLocalNotificationsPlugin>();
    await ios?.requestPermissions(alert: true, badge: true, sound: true);
  }

  /// Shows an immediate geofence alert. [id] lets callers overwrite their own
  /// prior alert (e.g. enter then exit) instead of stacking duplicates.
  Future<void> show({
    required int id,
    required String title,
    required String body,
  }) =>
      _showOn(_channel, id: id, title: title, body: body);

  /// Shows an incoming FCM push as a heads-up notification (used by the
  /// foreground `onMessage` handler — the OS suppresses the system tray
  /// notification while the app is in the foreground).
  Future<void> showPush({
    required int id,
    required String title,
    required String body,
    String? payload,
  }) =>
      _showOn(_pushChannel,
          id: id, title: title, body: body, payload: payload);

  Future<void> _showOn(
    AndroidNotificationChannel channel, {
    required int id,
    required String title,
    required String body,
    String? payload,
  }) async {
    // init() can throw in a background-service isolate (plugin quirks /
    // no Activity for a permission prompt). Don't let that bubble out and get
    // swallowed by the microtask that fires geofence alerts — log it and
    // still attempt the show; the channel was already created by the UI
    // isolate's init() at app launch, so the alert usually lands anyway.
    if (!_initialised) {
      try {
        await init();
      } catch (e) {
        await DebugLogService.instance.log(
          '[notification] init() failed inside show() — attempting anyway: $e',
        );
      }
    }
    final details = NotificationDetails(
      android: AndroidNotificationDetails(
        channel.id,
        channel.name,
        channelDescription: channel.description,
        importance: Importance.high,
        priority: Priority.high,
        // White silhouette small icon (tinted by the system); the colourful
        // brand mark rides along as the large icon.
        icon: 'ic_notification',
        largeIcon: const DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
      ),
      iOS: const DarwinNotificationDetails(),
    );
    try {
      await _plugin.show(id, title, body, details, payload: payload);
      await DebugLogService.instance
          .log('[notification] shown id=$id title="$title"');
    } catch (e, st) {
      if (kDebugMode) debugPrint('[notification] show failed: $e');
      await DebugLogService.instance
          .log('[notification] show FAILED id=$id title="$title" err=$e $st');
    }
  }
}
